version: "3"
services:
  frontend:
    build:
      context: music-pred-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  flaskserver:
    build:
      context: Python_Items
      dockerfile: Dockerfile
    ports:
      - "3500:3500"